import { Box, Container, Stack, VStack } from '@chakra-ui/react';
import Head from 'next/head';
import Link from 'next/link';
import type { FC } from 'react';

const LINKS_INDEX = [
  { href: '/index1', name: 'index1' },
  { href: '/index2', name: 'index2' },
  { href: '/index3', name: 'index3' },
  { href: '/index4', name: 'index4' },
  { href: '/index5', name: 'index5' },
] as const;

type Props = {
  href: indexHrefType;
  name: indexNameType;
};

export const LinkList: FC<Props> = ({ href, name }) => {
  return (
    <Box w='80px' p={2}>
      <Link href={href}>{name}</Link>
    </Box>
  );
};

type indexHrefType = typeof LINKS_INDEX[number]['href'];
type indexNameType = typeof LINKS_INDEX[number]['name'];

export default function Home() {
  return (
    <div>
      <Head>
        <title>doctormate</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <VStack>
          <Container maxW='md' bg='blue.600' color='white' my={20} borderRadius={'md'}>
            <Stack direction={['column', 'row']} spacing='24px'>
              {LINKS_INDEX.map((link) => {
                return <LinkList key={link.href} href={link.href} name={link.name} />;
              })}
            </Stack>
          </Container>
        </VStack>
      </main>
    </div>
  );
}
